"""changed password harsh 

Revision ID: 152bcdcafe91
Revises: 03f00807a3f8
Create Date: 2018-02-07 04:30:49.813710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152bcdcafe91'
down_revision = '03f00807a3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
