"""add votes 

Revision ID: 596ba870c3b2
Revises: 9db154dece0f
Create Date: 2018-02-09 01:04:28.024570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596ba870c3b2'
down_revision = '9db154dece0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitch_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitch', ['pitches_id'], ['id'])
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_id_fkey', 'comments', 'pitch', ['pitch_id'], ['id'])
    op.drop_column('comments', 'pitches_id')
    # ### end Alembic commands ###
