"""add the  table

Revision ID: 75edfc815e26
Revises: 26d6a18f3fbe
Create Date: 2018-02-11 00:37:22.570065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75edfc815e26'
down_revision = '26d6a18f3fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
