"""Initial 

Revision ID: db1faf79b407
Revises: 4746fd5ddd95
Create Date: 2018-02-06 15:20:56.507600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1faf79b407'
down_revision = '4746fd5ddd95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Profile')
    op.drop_table('Submission')
    op.drop_table('roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    op.create_table('Submission',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Submission_id_seq"\'::regclass)'), nullable=False),
    sa.Column('details', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Submission_pkey')
    )
    op.create_table('Profile',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Profile_id_seq"\'::regclass)'), nullable=False),
    sa.Column('details', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nickname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Profile_pkey')
    )
    op.drop_table('users')
    op.drop_table('category')
    # ### end Alembic commands ###
